// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkL0-OSOUkL8J-DdISrl8wLWhbdxiCshg',
    appId: '1:240953421387:ios:8aa33f40cc39a63080e7ce',
    messagingSenderId: '240953421387',
    projectId: 'movies-8001a',
    storageBucket: 'movies-8001a.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkL0-OSOUkL8J-DdISrl8wLWhbdxiCshg',
    appId: '1:240953421387:ios:8aa33f40cc39a63080e7ce',
    messagingSenderId: '240953421387',
    projectId: 'movies-8001a',
    storageBucket: 'movies-8001a.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8DBQyKYtEWmjO5NwJK0p9viS3GIkQpdQ',
    appId: '1:240953421387:android:601706932812d7bc80e7ce',
    messagingSenderId: '240953421387',
    projectId: 'movies-8001a',
    storageBucket: 'movies-8001a.firebasestorage.app',
  );
}
